version: "3"

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres # データベースのユーザー名
      POSTGRES_PASSWORD: root # データベースのパスワード
      POSTGRES_DB: learn-link # 初期に作成するデータベース名
    ports:
      - "35432:5432" # localhost:15432をコンテナの5432にマッピング
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
